name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Initialize Go module
      run: go mod init github.com/VishwaS-22/CICD-using-GitHub-Actions

    - name: Build
      run: go build -v ./src/Golang/main.go

    - name: Test
      run: go test -v ./src/Golang/main.go
